"""empty message

Revision ID: f76f55f9bb59
Revises: 
Create Date: 2017-01-09 11:33:31.094000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f76f55f9bb59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('CommentID', sa.String(length=64), nullable=False),
    sa.Column('PostID', sa.String(length=64), nullable=True),
    sa.Column('Name', sa.String(length=128), nullable=True),
    sa.Column('Comment', sa.Text(), nullable=True),
    sa.Column('CommentTo', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('CommentID')
    )
    op.create_table('posts',
    sa.Column('Author', sa.String(length=64), nullable=True),
    sa.Column('Image_Location', sa.String(length=64), nullable=True),
    sa.Column('Image_Caption', sa.String(length=64), nullable=True),
    sa.Column('Title', sa.String(length=120), nullable=False),
    sa.Column('Lead', sa.String(length=512), nullable=True),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Text', sa.Text(), nullable=True),
    sa.Column('Primary_Tag', sa.String(length=256), nullable=True),
    sa.Column('Secondary_Tag', sa.String(length=256), nullable=True),
    sa.Column('Views', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Title'),
    sa.UniqueConstraint('Image_Location'),
    sa.UniqueConstraint('Title')
    )
    op.create_table('test',
    sa.Column('col', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('col')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.drop_table('posts')
    op.drop_table('comments')
    ### end Alembic commands ###
